### ISSUE TITLE
"Cannot find module ckeditor4-integrations-common" error after upgrading to 2.2.0

### ISSUE THREAD

**Issue by nzacca** [ckeditor/ckeditor4-angular#191]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Install ckeditor4-angular 2.2.0
2. Examine the dependencies of ckeditor in the lock file

### Expected result

`ckeditor4-integrations-common` should be installed as dependency.

### Actual result

`ckeditor4-integrations-common` is not installed. Components are throwing errors that it cannot find `ckeditor4-integrations-common` for example:

```
Cannot find module 'ckeditor4-integrations-common' from '../../node_modules/ckeditor4-angular/bundles/ckeditor4-angular.umd.js'
```

## Other details

* CKEditor version: 2.2.0

`package.json` in the tar file does not appear to have `ckeditor4-integrations-common` listed in the dependencies: https://registry.npmjs.org/ckeditor4-angular/-/ckeditor4-angular-2.2.0.tgz

`package.json` in root does: https://github.com/ckeditor/ckeditor4-angular/blob/v2.2.0/package.json#L30

`package.json` in the distribution does not: https://github.com/ckeditor/ckeditor4-angular/blob/v2.2.0/dist/package.json#L34

**Comment by MMMalik** [comment]
Confirmed. Package `ckeditor4-integrations-common` is missing inside [nested package.json](https://github.com/ckeditor/ckeditor4-angular/blob/v2.2.0/src/ckeditor/package.json#L44) `dependencies` field.

**Comment by Dumluregn** [comment]
Closed in https://github.com/ckeditor/ckeditor4-angular/pull/193.
